# Google Analytics
google_analytics: UA-192900-3
title: "Unofficial R8 Reference"
theme: jekyll-theme-leap-day
repository: preemptive/r8-docs
defaults:
    - scope:
        path: "assets/img"
      values:
        image: true
